### PR TITLE
fix(plugin): cancel last timer before start another

### LINKED ISSUE #26: cancel last timer before start another.
I guess vim.defer_fn() won't do this automatically, maybe we should do it ourselves

### PR DESCRIPTION
**Pull request by Sduby22**
fix #26

### CODE REVIEW

File: lua/better_escape.lua [hunk 1]
```diff
@@ -12,11 +13,20 @@ local flag = false
...
+
+  if timer then
+    uv.stop_timer(timer)
+    uv.close(timer)
+    timer = nil
+  end
+  
   vim.defer_fn(function()
     flag = false
+    timer = nil
```
Comment (max397574) [inline lua/better_escape.lua:29]: Isn't `timer` `nil`at the beginning and always stays `nil`?

Comment (Sduby22) [reply lua/better_escape.lua:29]: sorry,I forgot to set timer variable by `timer = vim.defer_fn()`. Fixed now.

**Comment by max397574** [comment]
Thank you a lot for your help
